#!/bin/bash

i=0

for bpred in nottaken taken perfect bimod 2lev comb
do
  ((i++))
  echo "$i start" 1>&2
  echo -n "bpred:$bpred " > "temp/"$i"sim.out"
  ./jack-run-wattch "-bpred $bpred -ruu:size 16 -lsq:size 8 -fetch:ifqsize 8 -issue:width 4 -decode:width 8 -commit:width 8" 2>&1 |
    grep -E 'sim_IPC|# total power per cycle_cc1' |
    grep -E -o '[0-9]+.?[0-9]*' >> "temp/"$i"sim.out" &&
    echo "$i done" 1>&2 &
done

wait

for ((j=1;j<=$i;j++))
do
  cat "temp/"$j"sim.out" | echo `perl -ne 'chomp and print'`
done