#!/bin/bash

i=0

for ifqsize in 2 4 8 16 32 64
do
  for issuewidth in 2 4 8 16 32 64
  do
    for decodewidth in 2 4 8 16 32 64
    do
      for commitwidth in 2 4 8 16 32 64
      do
        ((i++))
        echo "$i start" 1>&2
        echo -n "ifq:$ifqsize iss:$issuewidth dec:$decodewidth com:$commitwidth " > "temp/"$i"sim.out"
        ./jack-run-wattch "-ruu:size 16 -lsq:size 8 -fetch:ifqsize $ifqsize -issue:width $issuewidth -decode:width $decodewidth -commit:width $commitwidth" 2>&1 |
          grep -E 'sim_IPC|# total power per cycle_cc1' |
          grep -E -o '[0-9]+.?[0-9]*' >> "temp/"$i"sim.out" &&
          echo "$i done" 1>&2 &
      done
    done
  done
done

wait

for ((j=1;j<=$i;j++))
do
  cat "temp/"$j"sim.out" | echo `perl -ne 'chomp and print'`
done