#!/bin/bash

i=0

for params in "-ruu:size 16" "-lsq:size 8" "-fetch:ifqsize 8" "-decode:width 8" "-issue:width 4" "-commit:width 8" "-bpred comb" "-mem:width 1" "-res:ialu 2" "-res:imult 8" "-res:fpalu 1" "-res:fpmult 8"
do
  ((i++))
  echo "$i start" 1>&2
  echo -n "$params " > "temp/"$i"sim.out"
  ./jack-run-wattch "$params" 2>&1 |
    grep -E 'sim_IPC|# total power per cycle_cc1' |
    grep -E -o '[0-9]+.?[0-9]*' >> "temp/"$i"sim.out" &&
    echo "$i done" 1>&2 &
done

wait

for ((j=1;j<=$i;j++))
do
  cat "temp/"$j"sim.out" | echo `perl -ne 'chomp and print'`
done