#!/bin/bash

i=0

for ialu in 1 2 4 8
do
  for imult in 1 2 4 8
  do
    for fpalu in 1 2 4 8
    do
      for fpmult in 1 2 4 8
      do
        ((i++))
        echo "$i start" 1>&2
        echo -n "ialu:$ialu imult:$imult fpalu:$fpalu fpmult:$fpmult " > "temp/"$i"sim.out"
        ./jack-run-wattch "-res:ialu $ialu -res:imult $imult -res:fpalu $fpalu -res:fpmult $fpmult -mem:width 1 -bpred comb -ruu:size 16 -lsq:size 8 -fetch:ifqsize 8 -issue:width 4 -decode:width 8 -commit:width 8" 2>&1 |
          grep -E 'sim_IPC|# total power per cycle_cc1' |
          grep -E -o '[0-9]+.?[0-9]*' >> "temp/"$i"sim.out" &&
          echo "$i done" 1>&2 &
      done
    done
  done
done

wait

for ((j=1;j<=$i;j++))
do
  cat "temp/"$j"sim.out" | echo `perl -ne 'chomp and print'`
done